name: teste_dvc
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2

      - name: setup r
        uses: r-lib/actions/setup-r@master

      - name: setup dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libssl-dev
          sudo apt-get install libxml2-dev
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: run analysis
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add figure to the report
          cml-publish plot.png --md >> report.md
          # Add table
          cat cm.html >> report.md

          cml-send-comment report.md
